theme:          jekyll-theme-cayman
title:          If I'm Going to be Frank
description:    And I always am...
author:         FrankD412
locale:         en_US
url:            https://frankd412.github.io
