theme:          jekyll-theme-cayman
title:          Frank Di Natale
description:    If I'm going to be Frank... And I always am.
author:         FrankD412
locale:         en_US
url:            https://frankd412.github.io
